// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as AnotherHelloWorld$ReactTemplate from "./AnotherHelloWorld.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, AnotherHelloWorld$ReactTemplate.make("Erlangga", /* array */[])), "index1");

export {
  
}
/*  Not a pure module */
